#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.

possibleParentDirectories=(
	"${HOME}/Documents"
	"${PROJECTS}"
	"${RESOURCES}/Repositories"
)

for directory in "${RESOURCES}/Repositories"/*; do
	possibleParentDirectories+="${directory}"
done

if [[ ! -z "${1}" ]]; then
	for possibleParentDirectory in "${possibleParentDirectories[@]}"; do
		if [[ -s "${possibleParentDirectory}/${1}" ]]; then
			cd "${possibleParentDirectory}/${1}"
		fi
	done
fi
