#!/usr/bin/env bash

if [[ "$1" == "0000000000000000000000000000000000000000" ]]; then
	# This must be a new repo being cloned
	exit
fi

parentDirectory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)

source "$parentDirectory"/common.sh $1 $2

check_run package.json "npm_config_package_lock=false npm install"
