#!/usr/bin/env bash

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
git lfs post-merge "$@"

parentDirectory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)

source "${parentDirectory}"/common.sh "" # Note: need to pass an empty string to override the arguments for this script

check_run package.json "npm_config_package_lock=false npm install"
