cask_args appdir: '/Applications'

tap "homebrew/bundle"
tap "edahlseng/core"
tap "golangci/tap"
tap "mongodb/brew"

brew "awscli"
brew "clang-format"
brew "clojure"
brew "conan"
brew "coreutils"
brew "csvkit"
brew "direnv"
brew "doxygen"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gdb"
brew "ghc"
brew "ghdl"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnu-tar"
brew "go"
brew "gpg"
brew "graphviz"
brew "grep"
brew "gtkwave"
brew "iperf"
brew "jq"
brew "kakoune"
brew "kops"
brew "kubectl"
brew "kubernetes-helm"
brew "make"
brew "mas"
brew "mitmproxy"
brew "nvm"
brew "picocom"
brew "pipenv"
brew "postgresql"
brew "python3"
brew "rlwrap"
brew "sbcl"
brew "sops"
brew "task"
brew "tasksh"
brew "tfenv"
brew "tor"
brew "trash"
brew "wget"
brew "youtube-dl"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "edahlseng/core/clang-tidy"
brew "edahlseng/core/git-sweep"
brew "edahlseng/core/swift-format", args: ["HEAD"]
brew "golangci/tap/golangci-lint"
brew "mongodb/brew/mongodb-community"

cask "amazon-workspaces"
cask "anki"
cask "arc"
cask "arduino"
cask "atom"
cask "backblaze"
cask "brave-browser"
cask "dash"
cask "docker"
cask "expressvpn"
cask "figma"
cask "firefox"
cask "fly"
cask "font-fira-code"
cask "google-chrome"
cask "google-cloud-sdk"
cask "grammarly-desktop"
cask "handbrake"
cask "hyper"
cask "java"
cask "kicad"
cask "lastpass"
cask "linear-linear"
cask "lingon-x"
cask "mactex"
cask "mongodb-compass"
cask "ngrok"
cask "paragon-extfs"
cask "postman"
cask "saleae-logic"
cask "shotcut"
cask "sketch"
cask "skype"
cask "skyfonts"
cask "superhuman"
cask "tor-browser"
cask "vlc"
cask "wireshark"
cask "xquartz"
cask "zed"
cask "zeplin"

mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "Honey", id: 1472777122
mas "iConvert Icons", id: 515197296
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINER", id: 1463530746
mas "Magnet", id: 441258766
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Pocket", id: 568494494
mas "Slack", id: 803453959
mas "Snippety", id: 1530751461
mas "WeChat", id: 836500024
mas "Xcode", id: 497799835
